spring:
  application:
    name: prepovedia
  datasource:
    url: jdbc:postgresql://localhost:5432/bot?useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      defer-datasource-initialization: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          characterEncoding: utf8
          CharSet: utf8
          useUnicode: true
